#!/bin/bash

# ==========================================
# Interaction-to-PRD V4: Interviewer Agent
# ==========================================
# Purpose: Scans your source code, detects "Black Box" logic, and triggers a Smart Pause.
# Usage: ./interviewer.sh [source_directory]

SOURCE_DIR=${1:-"./src"} # Default to ./src if no arg provided
OUTPUT_GAP="gap_analysis.md"
OUTPUT_QUESTIONS="interview_questions.md"

echo "🤖 [Interviewer Agent] Scanning source code in: $SOURCE_DIR"

if [ ! -d "$SOURCE_DIR" ]; then
    echo "❌ Error: Directory $SOURCE_DIR not found."
    exit 1
fi

# 1. Identify Core Logic Files
# (Customize this list based on your project structure)
echo "   Reading key types and components..."
FILES=$(find "$SOURCE_DIR" -name "*.ts" -o -name "*.tsx" | head -n 5)
echo "   Sample files being analyzed:"
echo "$FILES"

# 2. Heuristic Gap Detection (Generic Rules)
echo "🔍 [Gap Detection] Running heuristic scan..."

# Rule A: Check for "Mock" or "TODO" which implies missing backend
MOCK_COUNT=$(grep -r "Mock" "$SOURCE_DIR" | wc -l)
TODO_COUNT=$(grep -r "TODO" "$SOURCE_DIR" | wc -l)

# Rule B: Check for undefined API calls (fetch/axios without defined interface)
API_CALLS=$(grep -r "fetch(" "$SOURCE_DIR" | wc -l)

# 3. Generate Gap Analysis Report
cat <<EOF > "$OUTPUT_GAP"
# Gap Analysis Report
> Generated by Output of Interviewer Agent

## Scan Summary
*   **Source Directory**: $SOURCE_DIR
*   **Potential Mocks found**: $MOCK_COUNT
*   **TODOs found**: $TODO_COUNT
*   **API Calls detected**: $API_CALLS

## Detected Ambiguities (Heuristic)
1.  **Backend Logic**: Found $API_CALLS API calls. Do you have the Swagger/OpenAPI spec for these?
2.  **Mock Data**: Found $MOCK_COUNT instances of "Mock". What is the real logic intended to replace these?
3.  **Complex Algorithms**: If there are any 'Engines' or 'Calculators' (e.g., IOM, Recommendation), please verify if source code is present.
EOF

# 4. Generate Interview Questions Template
cat <<EOF > "$OUTPUT_QUESTIONS"
# Interview Questions
> Please answer the following questions to bridge the gap between Frontend Code and Business Logic.

## Q1: Unresolved API Calls
I found API calls in the frontend (e.g., fetch request).
*   **Question**: For key APIs, what is the expected payload and response format?
*   **Context**: Code shows the call but not the backend handler.

## Q2: "Mock" Logic
I found 'Mock' data in the code.
*   **Question**: specific logic is missing? (e.g., is there a specific sorting algorithm or AI model behind this?)

## Q3: User Permissions
From the UI, I see different views/buttons.
*   **Question**: What are the specific User Roles (e.g., Admin, Viewer) and their permission boundaries?

## Q4: [Custom]
(Add any specific questions about 'Magic' features like AI, Recommendations, or complex Calculations here)
EOF

echo "✅ [Interviewer Agent] Analysis Complete."
echo "   Gap Report: $OUTPUT_GAP"
echo "   Questions:  $OUTPUT_QUESTIONS"
echo "👉 NEXT STEP: Edit '$OUTPUT_QUESTIONS' to add specific queries, then answer them in 'interview_answers.md'."
